// flow-typed signature: ea24dd3abbef8442c311ba76217f4afa
// flow-typed version: <<STUB>>/admin-interface-core_v1.11.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'admin-interface-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'admin-interface-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'admin-interface-core/dist/Column/Column' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Column/Interface/ColumnInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/EventEmitter/EventEmitter' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/EventEmitter/Interface/EventEmitterInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/EventEmitter/Type/HandlerType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/EventEmitter/Type/SubscriberType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/FieldFactory/FieldFactory' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/FieldTypeAbstract/FieldTypeAbstract' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/FieldTypeAbstract/Interface/FieldTypeInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/FieldTypeAbstract/Type/RoutingType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Filter/Filter' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Filter/Type/FilterHandlerType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Filter/Type/FilterType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/index' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/ModelAbstract/Interface/ModelInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/ModelAbstract/ModelAbstract' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/ModelAbstract/ModelBuilder' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/ModelAbstract/Type/FieldType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/PageAbstract/Interface/PageInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/PageAbstract/PageAbstract' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Plugin/Interface/PluginInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Plugin/Plugin' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Registry/ProxyInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Registry/Registries/ConfigRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Registry/Registries/FieldTypeRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Registry/Registries/MenuRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Registry/Registries/ModelRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Registry/Registries/PageRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Registry/Registries/WidgetRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Registry/Registry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Registry/Repository' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Registry/Type/MenuType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Tab/Interface/TabInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Tab/Tab' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Utils/Config/AdminInterfaceRc' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Utils/index' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Utils/Menu/Parser' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Utils/Sequelize/Query' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/Utils/Yaml/Parser' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/WidgetAbstract/Interface/WidgetAbstractInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/WidgetAbstract/Type/RoutingType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/WidgetAbstract/WidgetAbstract' {
  declare module.exports: any;
}

declare module 'admin-interface-core/dist/WidgetFactory/WidgetFactory' {
  declare module.exports: any;
}

declare module 'admin-interface-core/docs/scripts/linenumber' {
  declare module.exports: any;
}

declare module 'admin-interface-core/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'admin-interface-core/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'admin-interface-core/flow-typed/DataTable/DataTable' {
  declare module.exports: any;
}

declare module 'admin-interface-core/flow-typed/npm/jade_vx.x.x' {
  declare module.exports: any;
}

declare module 'admin-interface-core/flow-typed/npm/js-yaml_vx.x.x' {
  declare module.exports: any;
}

declare module 'admin-interface-core/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'admin-interface-core/flow-typed/npm/object-path_vx.x.x' {
  declare module.exports: any;
}

declare module 'admin-interface-core/flow-typed/npm/sequelize_vx.x.x' {
  declare module.exports: any;
}

declare module 'admin-interface-core/flow-typed/npm/yaml-include_vx.x.x' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Column/Column' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Column/Interface/ColumnInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/EventEmitter/EventEmitter' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/EventEmitter/Interface/EventEmitterInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/EventEmitter/Type/HandlerType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/EventEmitter/Type/SubscriberType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/FieldFactory/FieldFactory' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/FieldTypeAbstract/FieldTypeAbstract' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/FieldTypeAbstract/Interface/FieldTypeInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/FieldTypeAbstract/Type/RoutingType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Filter/Filter' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Filter/Type/FilterHandlerType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Filter/Type/FilterType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/index' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/ModelAbstract/Interface/ModelInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/ModelAbstract/ModelAbstract' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/ModelAbstract/ModelBuilder' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/ModelAbstract/Type/FieldType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/PageAbstract/Interface/PageInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/PageAbstract/PageAbstract' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Plugin/Interface/PluginInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Plugin/Plugin' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Registry/ProxyInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Registry/Registries/ConfigRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Registry/Registries/FieldTypeRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Registry/Registries/MenuRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Registry/Registries/ModelRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Registry/Registries/PageRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Registry/Registries/WidgetRegistry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Registry/Registry' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Registry/Repository' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Registry/Type/MenuType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Tab/Interface/TabInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Tab/Tab' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Utils/Config/AdminInterfaceRc' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Utils/index' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Utils/Menu/Parser' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Utils/Sequelize/Query' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/Utils/Yaml/Parser' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/WidgetAbstract/Interface/WidgetAbstractInterface' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/WidgetAbstract/Type/RoutingType' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/WidgetAbstract/WidgetAbstract' {
  declare module.exports: any;
}

declare module 'admin-interface-core/src/WidgetFactory/WidgetFactory' {
  declare module.exports: any;
}

// Filename aliases
declare module 'admin-interface-core/dist/Column/Column.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Column/Column'>;
}
declare module 'admin-interface-core/dist/Column/Interface/ColumnInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Column/Interface/ColumnInterface'>;
}
declare module 'admin-interface-core/dist/EventEmitter/EventEmitter.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/EventEmitter/EventEmitter'>;
}
declare module 'admin-interface-core/dist/EventEmitter/Interface/EventEmitterInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/EventEmitter/Interface/EventEmitterInterface'>;
}
declare module 'admin-interface-core/dist/EventEmitter/Type/HandlerType.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/EventEmitter/Type/HandlerType'>;
}
declare module 'admin-interface-core/dist/EventEmitter/Type/SubscriberType.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/EventEmitter/Type/SubscriberType'>;
}
declare module 'admin-interface-core/dist/FieldFactory/FieldFactory.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/FieldFactory/FieldFactory'>;
}
declare module 'admin-interface-core/dist/FieldTypeAbstract/FieldTypeAbstract.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/FieldTypeAbstract/FieldTypeAbstract'>;
}
declare module 'admin-interface-core/dist/FieldTypeAbstract/Interface/FieldTypeInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/FieldTypeAbstract/Interface/FieldTypeInterface'>;
}
declare module 'admin-interface-core/dist/FieldTypeAbstract/Type/RoutingType.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/FieldTypeAbstract/Type/RoutingType'>;
}
declare module 'admin-interface-core/dist/Filter/Filter.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Filter/Filter'>;
}
declare module 'admin-interface-core/dist/Filter/Type/FilterHandlerType.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Filter/Type/FilterHandlerType'>;
}
declare module 'admin-interface-core/dist/Filter/Type/FilterType.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Filter/Type/FilterType'>;
}
declare module 'admin-interface-core/dist/index.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/index'>;
}
declare module 'admin-interface-core/dist/ModelAbstract/Interface/ModelInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/ModelAbstract/Interface/ModelInterface'>;
}
declare module 'admin-interface-core/dist/ModelAbstract/ModelAbstract.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/ModelAbstract/ModelAbstract'>;
}
declare module 'admin-interface-core/dist/ModelAbstract/ModelBuilder.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/ModelAbstract/ModelBuilder'>;
}
declare module 'admin-interface-core/dist/ModelAbstract/Type/FieldType.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/ModelAbstract/Type/FieldType'>;
}
declare module 'admin-interface-core/dist/PageAbstract/Interface/PageInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/PageAbstract/Interface/PageInterface'>;
}
declare module 'admin-interface-core/dist/PageAbstract/PageAbstract.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/PageAbstract/PageAbstract'>;
}
declare module 'admin-interface-core/dist/Plugin/Interface/PluginInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Plugin/Interface/PluginInterface'>;
}
declare module 'admin-interface-core/dist/Plugin/Plugin.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Plugin/Plugin'>;
}
declare module 'admin-interface-core/dist/Registry/ProxyInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Registry/ProxyInterface'>;
}
declare module 'admin-interface-core/dist/Registry/Registries/ConfigRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Registry/Registries/ConfigRegistry'>;
}
declare module 'admin-interface-core/dist/Registry/Registries/FieldTypeRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Registry/Registries/FieldTypeRegistry'>;
}
declare module 'admin-interface-core/dist/Registry/Registries/MenuRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Registry/Registries/MenuRegistry'>;
}
declare module 'admin-interface-core/dist/Registry/Registries/ModelRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Registry/Registries/ModelRegistry'>;
}
declare module 'admin-interface-core/dist/Registry/Registries/PageRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Registry/Registries/PageRegistry'>;
}
declare module 'admin-interface-core/dist/Registry/Registries/WidgetRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Registry/Registries/WidgetRegistry'>;
}
declare module 'admin-interface-core/dist/Registry/Registry.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Registry/Registry'>;
}
declare module 'admin-interface-core/dist/Registry/Repository.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Registry/Repository'>;
}
declare module 'admin-interface-core/dist/Registry/Type/MenuType.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Registry/Type/MenuType'>;
}
declare module 'admin-interface-core/dist/Tab/Interface/TabInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Tab/Interface/TabInterface'>;
}
declare module 'admin-interface-core/dist/Tab/Tab.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Tab/Tab'>;
}
declare module 'admin-interface-core/dist/Utils/Config/AdminInterfaceRc.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Utils/Config/AdminInterfaceRc'>;
}
declare module 'admin-interface-core/dist/Utils/index.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Utils/index'>;
}
declare module 'admin-interface-core/dist/Utils/Menu/Parser.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Utils/Menu/Parser'>;
}
declare module 'admin-interface-core/dist/Utils/Sequelize/Query.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Utils/Sequelize/Query'>;
}
declare module 'admin-interface-core/dist/Utils/Yaml/Parser.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/Utils/Yaml/Parser'>;
}
declare module 'admin-interface-core/dist/WidgetAbstract/Interface/WidgetAbstractInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/WidgetAbstract/Interface/WidgetAbstractInterface'>;
}
declare module 'admin-interface-core/dist/WidgetAbstract/Type/RoutingType.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/WidgetAbstract/Type/RoutingType'>;
}
declare module 'admin-interface-core/dist/WidgetAbstract/WidgetAbstract.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/WidgetAbstract/WidgetAbstract'>;
}
declare module 'admin-interface-core/dist/WidgetFactory/WidgetFactory.js' {
  declare module.exports: $Exports<'admin-interface-core/dist/WidgetFactory/WidgetFactory'>;
}
declare module 'admin-interface-core/docs/scripts/linenumber.js' {
  declare module.exports: $Exports<'admin-interface-core/docs/scripts/linenumber'>;
}
declare module 'admin-interface-core/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'admin-interface-core/docs/scripts/prettify/lang-css'>;
}
declare module 'admin-interface-core/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'admin-interface-core/docs/scripts/prettify/prettify'>;
}
declare module 'admin-interface-core/flow-typed/DataTable/DataTable.js' {
  declare module.exports: $Exports<'admin-interface-core/flow-typed/DataTable/DataTable'>;
}
declare module 'admin-interface-core/flow-typed/npm/jade_vx.x.x.js' {
  declare module.exports: $Exports<'admin-interface-core/flow-typed/npm/jade_vx.x.x'>;
}
declare module 'admin-interface-core/flow-typed/npm/js-yaml_vx.x.x.js' {
  declare module.exports: $Exports<'admin-interface-core/flow-typed/npm/js-yaml_vx.x.x'>;
}
declare module 'admin-interface-core/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'admin-interface-core/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'admin-interface-core/flow-typed/npm/object-path_vx.x.x.js' {
  declare module.exports: $Exports<'admin-interface-core/flow-typed/npm/object-path_vx.x.x'>;
}
declare module 'admin-interface-core/flow-typed/npm/sequelize_vx.x.x.js' {
  declare module.exports: $Exports<'admin-interface-core/flow-typed/npm/sequelize_vx.x.x'>;
}
declare module 'admin-interface-core/flow-typed/npm/yaml-include_vx.x.x.js' {
  declare module.exports: $Exports<'admin-interface-core/flow-typed/npm/yaml-include_vx.x.x'>;
}
declare module 'admin-interface-core/index' {
  declare module.exports: $Exports<'admin-interface-core'>;
}
declare module 'admin-interface-core/index.js' {
  declare module.exports: $Exports<'admin-interface-core'>;
}
declare module 'admin-interface-core/src/Column/Column.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Column/Column'>;
}
declare module 'admin-interface-core/src/Column/Interface/ColumnInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Column/Interface/ColumnInterface'>;
}
declare module 'admin-interface-core/src/EventEmitter/EventEmitter.js' {
  declare module.exports: $Exports<'admin-interface-core/src/EventEmitter/EventEmitter'>;
}
declare module 'admin-interface-core/src/EventEmitter/Interface/EventEmitterInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/src/EventEmitter/Interface/EventEmitterInterface'>;
}
declare module 'admin-interface-core/src/EventEmitter/Type/HandlerType.js' {
  declare module.exports: $Exports<'admin-interface-core/src/EventEmitter/Type/HandlerType'>;
}
declare module 'admin-interface-core/src/EventEmitter/Type/SubscriberType.js' {
  declare module.exports: $Exports<'admin-interface-core/src/EventEmitter/Type/SubscriberType'>;
}
declare module 'admin-interface-core/src/FieldFactory/FieldFactory.js' {
  declare module.exports: $Exports<'admin-interface-core/src/FieldFactory/FieldFactory'>;
}
declare module 'admin-interface-core/src/FieldTypeAbstract/FieldTypeAbstract.js' {
  declare module.exports: $Exports<'admin-interface-core/src/FieldTypeAbstract/FieldTypeAbstract'>;
}
declare module 'admin-interface-core/src/FieldTypeAbstract/Interface/FieldTypeInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/src/FieldTypeAbstract/Interface/FieldTypeInterface'>;
}
declare module 'admin-interface-core/src/FieldTypeAbstract/Type/RoutingType.js' {
  declare module.exports: $Exports<'admin-interface-core/src/FieldTypeAbstract/Type/RoutingType'>;
}
declare module 'admin-interface-core/src/Filter/Filter.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Filter/Filter'>;
}
declare module 'admin-interface-core/src/Filter/Type/FilterHandlerType.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Filter/Type/FilterHandlerType'>;
}
declare module 'admin-interface-core/src/Filter/Type/FilterType.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Filter/Type/FilterType'>;
}
declare module 'admin-interface-core/src/index.js' {
  declare module.exports: $Exports<'admin-interface-core/src/index'>;
}
declare module 'admin-interface-core/src/ModelAbstract/Interface/ModelInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/src/ModelAbstract/Interface/ModelInterface'>;
}
declare module 'admin-interface-core/src/ModelAbstract/ModelAbstract.js' {
  declare module.exports: $Exports<'admin-interface-core/src/ModelAbstract/ModelAbstract'>;
}
declare module 'admin-interface-core/src/ModelAbstract/ModelBuilder.js' {
  declare module.exports: $Exports<'admin-interface-core/src/ModelAbstract/ModelBuilder'>;
}
declare module 'admin-interface-core/src/ModelAbstract/Type/FieldType.js' {
  declare module.exports: $Exports<'admin-interface-core/src/ModelAbstract/Type/FieldType'>;
}
declare module 'admin-interface-core/src/PageAbstract/Interface/PageInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/src/PageAbstract/Interface/PageInterface'>;
}
declare module 'admin-interface-core/src/PageAbstract/PageAbstract.js' {
  declare module.exports: $Exports<'admin-interface-core/src/PageAbstract/PageAbstract'>;
}
declare module 'admin-interface-core/src/Plugin/Interface/PluginInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Plugin/Interface/PluginInterface'>;
}
declare module 'admin-interface-core/src/Plugin/Plugin.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Plugin/Plugin'>;
}
declare module 'admin-interface-core/src/Registry/ProxyInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Registry/ProxyInterface'>;
}
declare module 'admin-interface-core/src/Registry/Registries/ConfigRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Registry/Registries/ConfigRegistry'>;
}
declare module 'admin-interface-core/src/Registry/Registries/FieldTypeRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Registry/Registries/FieldTypeRegistry'>;
}
declare module 'admin-interface-core/src/Registry/Registries/MenuRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Registry/Registries/MenuRegistry'>;
}
declare module 'admin-interface-core/src/Registry/Registries/ModelRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Registry/Registries/ModelRegistry'>;
}
declare module 'admin-interface-core/src/Registry/Registries/PageRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Registry/Registries/PageRegistry'>;
}
declare module 'admin-interface-core/src/Registry/Registries/WidgetRegistry.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Registry/Registries/WidgetRegistry'>;
}
declare module 'admin-interface-core/src/Registry/Registry.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Registry/Registry'>;
}
declare module 'admin-interface-core/src/Registry/Repository.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Registry/Repository'>;
}
declare module 'admin-interface-core/src/Registry/Type/MenuType.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Registry/Type/MenuType'>;
}
declare module 'admin-interface-core/src/Tab/Interface/TabInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Tab/Interface/TabInterface'>;
}
declare module 'admin-interface-core/src/Tab/Tab.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Tab/Tab'>;
}
declare module 'admin-interface-core/src/Utils/Config/AdminInterfaceRc.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Utils/Config/AdminInterfaceRc'>;
}
declare module 'admin-interface-core/src/Utils/index.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Utils/index'>;
}
declare module 'admin-interface-core/src/Utils/Menu/Parser.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Utils/Menu/Parser'>;
}
declare module 'admin-interface-core/src/Utils/Sequelize/Query.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Utils/Sequelize/Query'>;
}
declare module 'admin-interface-core/src/Utils/Yaml/Parser.js' {
  declare module.exports: $Exports<'admin-interface-core/src/Utils/Yaml/Parser'>;
}
declare module 'admin-interface-core/src/WidgetAbstract/Interface/WidgetAbstractInterface.js' {
  declare module.exports: $Exports<'admin-interface-core/src/WidgetAbstract/Interface/WidgetAbstractInterface'>;
}
declare module 'admin-interface-core/src/WidgetAbstract/Type/RoutingType.js' {
  declare module.exports: $Exports<'admin-interface-core/src/WidgetAbstract/Type/RoutingType'>;
}
declare module 'admin-interface-core/src/WidgetAbstract/WidgetAbstract.js' {
  declare module.exports: $Exports<'admin-interface-core/src/WidgetAbstract/WidgetAbstract'>;
}
declare module 'admin-interface-core/src/WidgetFactory/WidgetFactory.js' {
  declare module.exports: $Exports<'admin-interface-core/src/WidgetFactory/WidgetFactory'>;
}
