// flow-typed signature: fd7ecdc00153b8eaf59338445bba116c
// flow-typed version: <<STUB>>/container-ioc_v1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'container-ioc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'container-ioc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'container-ioc/dist/lib/container.interface' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/container' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/decorators' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/exceptions' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/index' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/injection-token' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/interfaces' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/metadata/annotator-provider' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/metadata/index' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/metadata/keys' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/metadata/metadata-annotator.interface' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/metadata/reflect-metadata-annotator' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/metadata/static-metadata-annotator' {
  declare module.exports: any;
}

declare module 'container-ioc/dist/lib/registry-data' {
  declare module.exports: any;
}

// Filename aliases
declare module 'container-ioc/dist/lib/container.interface.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/container.interface'>;
}
declare module 'container-ioc/dist/lib/container.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/container'>;
}
declare module 'container-ioc/dist/lib/decorators.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/decorators'>;
}
declare module 'container-ioc/dist/lib/exceptions.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/exceptions'>;
}
declare module 'container-ioc/dist/lib/index.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/index'>;
}
declare module 'container-ioc/dist/lib/injection-token.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/injection-token'>;
}
declare module 'container-ioc/dist/lib/interfaces.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/interfaces'>;
}
declare module 'container-ioc/dist/lib/metadata/annotator-provider.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/metadata/annotator-provider'>;
}
declare module 'container-ioc/dist/lib/metadata/index.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/metadata/index'>;
}
declare module 'container-ioc/dist/lib/metadata/keys.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/metadata/keys'>;
}
declare module 'container-ioc/dist/lib/metadata/metadata-annotator.interface.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/metadata/metadata-annotator.interface'>;
}
declare module 'container-ioc/dist/lib/metadata/reflect-metadata-annotator.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/metadata/reflect-metadata-annotator'>;
}
declare module 'container-ioc/dist/lib/metadata/static-metadata-annotator.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/metadata/static-metadata-annotator'>;
}
declare module 'container-ioc/dist/lib/registry-data.js' {
  declare module.exports: $Exports<'container-ioc/dist/lib/registry-data'>;
}
