// flow-typed signature: 08b5e27316bf1417a92fc52bef0f13b7
// flow-typed version: <<STUB>>/yaml-include_v1.2.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yaml-include'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yaml-include' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yaml-include/example/build' {
  declare module.exports: any;
}

declare module 'yaml-include/lib/dir' {
  declare module.exports: any;
}

declare module 'yaml-include/lib/file' {
  declare module.exports: any;
}

declare module 'yaml-include/test/test-issues' {
  declare module.exports: any;
}

declare module 'yaml-include/test/test-options' {
  declare module.exports: any;
}

declare module 'yaml-include/test/test-process-chdir-dir' {
  declare module.exports: any;
}

declare module 'yaml-include/test/test-process-chdir-file' {
  declare module.exports: any;
}

declare module 'yaml-include/test/test-swagger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yaml-include/example/build.js' {
  declare module.exports: $Exports<'yaml-include/example/build'>;
}
declare module 'yaml-include/index' {
  declare module.exports: $Exports<'yaml-include'>;
}
declare module 'yaml-include/index.js' {
  declare module.exports: $Exports<'yaml-include'>;
}
declare module 'yaml-include/lib/dir.js' {
  declare module.exports: $Exports<'yaml-include/lib/dir'>;
}
declare module 'yaml-include/lib/file.js' {
  declare module.exports: $Exports<'yaml-include/lib/file'>;
}
declare module 'yaml-include/test/test-issues.js' {
  declare module.exports: $Exports<'yaml-include/test/test-issues'>;
}
declare module 'yaml-include/test/test-options.js' {
  declare module.exports: $Exports<'yaml-include/test/test-options'>;
}
declare module 'yaml-include/test/test-process-chdir-dir.js' {
  declare module.exports: $Exports<'yaml-include/test/test-process-chdir-dir'>;
}
declare module 'yaml-include/test/test-process-chdir-file.js' {
  declare module.exports: $Exports<'yaml-include/test/test-process-chdir-file'>;
}
declare module 'yaml-include/test/test-swagger.js' {
  declare module.exports: $Exports<'yaml-include/test/test-swagger'>;
}
